export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_LOOMIANS_PENDING = 'REQUEST_LOOMIANS_PENDING';
export const REQUEST_LOOMIANS_SUCCESS = 'REQUEST_LOOMIANS_SUCCESS';
export const REQUEST_LOOMIANS_FAILED = 'REQUEST_LOOMIANS_FAILED';